#!/bin/bash

set -eu

package="$1"
version="$2"
exec_name="$3"
output_dir="$4"

npm install "$package@$version"
exec nexe "node_modules/$package/bin/$exec_name" -o "$output_dir" -r "node_modules/$package/**"
