#!/bin/bash -eu

libwebp_version=1.6.0

if [ -e work/libwebp ]; then
  rm -fr work/libwebp
fi

curl -o work/libwebp.tar.gz "https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-$libwebp_version-linux-x86-64.tar.gz"
tar xvzf work/libwebp.tar.gz -C work
mv "work/libwebp-$libwebp_version-linux-x86-64" work/libwebp
rm work/libwebp.tar.gz
