#!/bin/bash -eu

libwebp_version=1.6.0
libavif_version=1.3.0

if [ -e work/libwebp ]; then
  rm -fr work/libwebp
fi

if [ -e work/libavif ]; then
  rm -fr work/libavif
fi

curl -sSfL -o work/libwebp.tar.gz "https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-$libwebp_version-linux-x86-64.tar.gz"
tar xvzf work/libwebp.tar.gz -C work
mv "work/libwebp-$libwebp_version-linux-x86-64" work/libwebp
rm work/libwebp.tar.gz

curl -sSfL -o work/libavif.zip "https://github.com/AOMediaCodec/libavif/releases/download/v$libavif_version/linux-artifacts.zip"
mkdir -p work/libavif
unzip work/libavif.zip -d work/libavif
