name: CI

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
    - issue/*
    - dev/harai

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.15.0'
    - run: go build -o work/imgconv lambda/lambda.go
    - uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: work/imgconv

  release:
    needs: build
    # if: github.ref == 'refs/heads/master'
    if: github.ref == 'refs/heads/dev/harai'
    runs-on: ubuntu-20.04
    env:
      BUCKET_NAME: gutenberg-modrepo-modulerepobucket-99uoevgdqlvw
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: artifact
    - name: Generate build number
      uses: einaregilsson/build-number@v3
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        prefix: build_number_generator
    - name: Print new build number
      run: echo "Build number is $BUILD_NUMBER"
    - id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        tag_name: build-${{env.BUILD_NUMBER}}
        release_name: Build ${{env.BUILD_NUMBER}}
        draft: false
        prerelease: false
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: ap-northeast-1
    - run: aws s3 cp ./imgconv s3://${{env.BUCKET_NAME}}/imgconv/imgconv.build-${{env.BUILD_NUMBER}}-linux-amd64
